const DEFAULT_SHEET_ENDPOINT = "https://script.google.com/macros/s/AKfycbzUMwxgPYsHUNnzHbOXbOjkBdQ1_sD3L2QI890k5QAhquFAuflytlnp7Lje5uY6JnbAUw/exec";
const STORAGE_KEY = "kampusreach-workspace-v3";

const seedRecords = [
  { id: 352, institution: "Poltekkes Kemenkes Banten", category: "Politeknik", role: "Subbagian Administrasi Umum", phone: "0858-2146-6172", email: "direktorat@poltekkesbanten.ac.id", address: "Serang, Banten", region: "Banten", website: "https://poltekkesbanten.ac.id", confidence: 91, status: "Auto-stored", readiness: "Siap Dihubungi", evidence: "Situs resmi · halaman kontak", source: "Website resmi" },
  { id: 353, institution: "STKIP Surya", category: "Sekolah Tinggi", role: "Wakil Ketua III", phone: "0811-8207-728", email: "info@stkipsurya.ac.id", address: "Tangerang, Banten", region: "Banten", website: "https://stkipsurya.ac.id", confidence: 86, status: "Disetujui", readiness: "Siap Dihubungi", evidence: "Situs resmi · profil pimpinan", source: "Website resmi" },
  { id: 354, institution: "Pradita University", category: "Universitas", role: "Bagian Humas & Kerja Sama", phone: "0815-1300-9999", email: "info@pradita.ac.id", address: "Tangerang, Banten", region: "Banten", website: "https://pradita.ac.id", confidence: 89, status: "Auto-stored", readiness: "Follow-up", evidence: "Situs resmi · halaman kontak", source: "Website resmi" },
  { id: 355, institution: "Universitas Yuppentek Indonesia", category: "Universitas", role: "Bagian Humas & Kerja Sama", phone: "0812-1370-0049", email: "humas@uyi.ac.id", address: "Kota Tangerang", region: "Banten", website: "https://uyi.ac.id", confidence: 78, status: "Perlu Review", readiness: "Belum Dihubungi", evidence: "Direktori kampus · situs institusi", source: "Direktori publik" },
  { id: 356, institution: "UIN Sultan Maulana Hasanuddin Banten", category: "Universitas", role: "Biro Akademik & Kerja Sama", phone: "0254-200323", email: "humas@uinbanten.ac.id", address: "Serang, Banten", region: "Banten", website: "https://uinbanten.ac.id", confidence: 94, status: "Disetujui", readiness: "Siap Dihubungi", evidence: "Situs resmi · direktori unit", source: "Website resmi" },
  { id: 357, institution: "Institut Ilmu Al-Qur'an Jakarta", category: "Institut", role: "UPT Humas", phone: "0811-1144-873", email: "iiq@iiq.ac.id", address: "Tangerang Selatan", region: "Banten", website: "https://iiq.ac.id", confidence: 83, status: "Auto-stored", readiness: "Belum Dihubungi", evidence: "Situs resmi · footer kontak", source: "Website resmi" },
  { id: 358, institution: "Ma'had Aly Riyadul Jannah", category: "Institut", role: "Bagian Administrasi", phone: "0812-8049-9053", email: "mahadalyriyaduljannah@gmail.com", address: "Kota Tangerang", region: "Banten", website: "", confidence: 56, status: "Perlu Review", readiness: "Perlu Verifikasi", evidence: "Direktori publik · kontak belum terverifikasi", source: "Direktori publik" },
  { id: 359, institution: "Politeknik Penerbangan Indonesia Curug", category: "Politeknik", role: "Bagian Keuangan dan Umum", phone: "0813-1825-5567", email: "ppi@ppicurug.ac.id", address: "Tangerang, Banten", region: "Banten", website: "https://ppicurug.ac.id", confidence: 93, status: "Disetujui", readiness: "Siap Dihubungi", evidence: "Situs resmi · halaman layanan", source: "Website resmi" },
  { id: 360, institution: "Global Institute", category: "Institut", role: "Kontak Kerja Sama", phone: "021-552-2727", email: "kampus@global.ac.id", address: "Karawaci, Tangerang", region: "Banten", website: "https://global.ac.id", confidence: 81, status: "Auto-stored", readiness: "Follow-up", evidence: "Situs resmi · halaman kontak", source: "Website resmi" },
  { id: 361, institution: "STIKes Bani Saleh", category: "Sekolah Tinggi", role: "Humas / Administrasi", phone: "021-8834-5064", email: "info@stikesbanisaleh.ac.id", address: "Bekasi, Jawa Barat", region: "Jawa Barat", website: "https://stikesbanisaleh.ac.id", confidence: 76, status: "Perlu Review", readiness: "Belum Dihubungi", evidence: "Situs resmi · kontak umum", source: "Website resmi" },
  { id: 362, institution: "Universitas Pendidikan Indonesia", category: "Universitas", role: "Direktorat Kerja Sama", phone: "022-2013163", email: "humas@upi.edu", address: "Bandung, Jawa Barat", region: "Jawa Barat", website: "https://upi.edu", confidence: 96, status: "Disetujui", readiness: "Siap Dihubungi", evidence: "Situs resmi · direktorat", source: "Website resmi" },
  { id: 363, institution: "Universitas Negeri Jakarta", category: "Universitas", role: "Kantor Humas dan Informasi Publik", phone: "021-4898486", email: "humas@unj.ac.id", address: "Jakarta Timur, DKI Jakarta", region: "DKI Jakarta", website: "https://unj.ac.id", confidence: 95, status: "Auto-stored", readiness: "Siap Dihubungi", evidence: "Situs resmi · kontak universitas", source: "Website resmi" }
];

const seedProjects = [
  { id: "prj-banten", name: "Kampus Banten untuk kerja sama", focus: "kampus, kerja sama, sertifikasi", roleFocus: "Humas, Kerja Sama, Akademik", region: "Banten", category: "Semua", mode: "Deep", sources: "Data contoh", sourceUrls: "", backend: false, status: "Data tersedia", resultIds: [352,353,354,355,356,357,358,359,360], createdAt: "2026-09-30T08:30:00.000Z", picName: "Khairul", retrieval: "9 kontak dari 9 institusi" },
  { id: "prj-jabar", name: "PIC kampus Jawa Barat", focus: "kontak humas dan kerja sama", roleFocus: "Humas, Kerja Sama", region: "Jawa Barat", category: "Semua", mode: "Strict", sources: "Data contoh", sourceUrls: "", backend: false, status: "Data tersedia", resultIds: [361,362], createdAt: "2026-09-29T04:15:00.000Z", picName: "Khairul", retrieval: "2 kontak dari 2 institusi" },
  { id: "prj-nasional", name: "Universitas negeri nasional", focus: "universitas negeri", roleFocus: "Humas, Akademik", region: "Indonesia", category: "Universitas", mode: "Deep", sources: "Data contoh", sourceUrls: "", backend: false, status: "Data tersedia", resultIds: [356,362,363], createdAt: "2026-09-28T06:00:00.000Z", picName: "Khairul", retrieval: "3 kontak dari 3 institusi" }
];

const stored = readStored();
const state = {
  view: "dashboard",
  records: stored.records?.length ? stored.records : seedRecords,
  projects: stored.projects?.length ? stored.projects : seedProjects,
  pic: stored.pic || { name: "", contact: "", unit: "" },
  settings: stored.settings || { sheetEndpoint: DEFAULT_SHEET_ENDPOINT, minConfidence: 65, safeMode: true },
  theme: localStorage.getItem("kampus-theme") || "light",
  selectedProject: stored.selectedProject || "all",
  downloadLog: stored.downloadLog || [],
  pendingSearch: false
};

const viewMeta = {
  dashboard: ["Dashboard", "Ringkasan workspace pencarian database kampus"], projects: ["Search Projects", "Kelola seluruh proyek pencarian tim"], review: ["Results & Review", "Tinjau hasil dan tangani data pengecualian"], database: ["Master Database", "Seluruh kontak publik yang tersimpan"], download: ["Download Center", "Ekspor data sesuai proyek dan filter"], settings: ["Settings & Safety", "Koneksi data dan aturan kualitas"], help: ["Bantuan", "Panduan singkat penggunaan workspace"]
};
const content = document.getElementById("content");
const modalBackdrop = document.getElementById("modalBackdrop");
const modalBody = document.getElementById("modalBody");
const toastEl = document.getElementById("toast");
document.body.classList.toggle("dark", state.theme === "dark");

function readStored() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}; } catch { return {}; } }
function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify({ records: state.records, projects: state.projects, pic: state.pic, settings: state.settings, selectedProject: state.selectedProject, downloadLog: state.downloadLog.slice(0, 12) })); }
const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c]));
const fmtDate = (value) => new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const initials = (text) => String(text).split(/\s+/).map((word) => word[0]).join("").slice(0, 2).toUpperCase();
const tagClass = (value) => ["Data tersedia", "Disetujui", "Siap Dihubungi"].includes(value) ? "green" : ["Sedang mencari", "Follow-up", "Auto-stored"].includes(value) ? "amber" : ["Error", "Perlu Review", "Perlu Verifikasi"].includes(value) ? "red" : "";
function showToast(message) { toastEl.textContent = message; toastEl.classList.add("show"); setTimeout(() => toastEl.classList.remove("show"), 2800); }
function projectRecords(projectId) { if (!projectId || projectId === "all") return state.records; const project = state.projects.find((item) => item.id === projectId); const ids = new Set((project?.resultIds || []).map(String)); return project ? state.records.filter((record) => ids.has(String(record.id))) : []; }
function updateChrome() {
  const [title, subtitle] = viewMeta[state.view]; document.getElementById("pageTitle").textContent = title; document.getElementById("pageSubtitle").textContent = subtitle;
  document.querySelectorAll(".nav-item").forEach((item) => item.classList.toggle("active", item.dataset.view === state.view));
  document.getElementById("databaseBadge").textContent = state.records.length.toLocaleString("id-ID");
  document.getElementById("reviewBadge").textContent = state.records.filter((record) => record.status === "Perlu Review" || record.confidence < state.settings.minConfidence).length;
  const PIC_ICON = `<svg class="btn-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="8" r="5"/><path d="M20 21a8 8 0 0 0-16 0"/></svg>`;
  document.getElementById("picButton").innerHTML = state.pic.name ? `${PIC_ICON} ${esc(state.pic.name)}` : `${PIC_ICON} Isi identitas PIC`;
  document.getElementById("sidebar").classList.remove("open");
}
function render() { updateChrome(); const views = { dashboard: dashboardView, projects: projectsView, review: reviewView, database: databaseView, download: downloadView, settings: settingsView, help: helpView }; content.innerHTML = views[state.view](); bindViewEvents(); }

function dashboardView() {
  const exceptions = state.records.filter((r) => r.status === "Perlu Review" || r.confidence < state.settings.minConfidence).length;
  const ready = state.records.filter((r) => r.readiness === "Siap Dihubungi").length;
  const avg = Math.round(state.records.reduce((sum, r) => sum + Number(r.confidence || 0), 0) / Math.max(1, state.records.length));
  const latest = [...state.projects].sort((a,b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0,4);
  return `<div class="notice"><div><div class="notice-title">Workspace publik — <strong>${state.pic.name ? `PIC aktif: ${esc(state.pic.name)}` : "identitas PIC belum diisi"}</strong></div><p>${state.pic.name ? "Pencarian baru dan keputusan review akan dicatat atas PIC ini." : "Isi nama serta email/ID sebelum membuat pencarian baru."}</p></div><button class="outline-button" id="noticePicButton">${state.pic.name ? "Ubah identitas" : "Isi identitas PIC"}</button></div>
  <section class="hero"><div class="eyebrow">CONFIGURABLE SEARCH · SHARED PIC WORKSPACE</div><h2>Cari, tinjau, dan simpan database kampus dalam satu alur kerja.</h2><p>Buat proyek berdasarkan fokus, wilayah, peran PIC kampus, dan sumber. Hasil dapat direview, diperbarui statusnya, lalu diekspor untuk kebutuhan follow-up.</p><div class="button-row"><button class="primary-button" id="heroSearch">Mulai pencarian</button><button class="secondary-button" data-go="database">Buka Master Database</button></div></section>
  <section class="metrics"><div class="metric"><div class="metric-label">Search Projects</div><div class="metric-value">${state.projects.length}</div><div class="metric-trend">${state.projects.filter(p => p.status === "Sedang mencari").length} sedang berjalan</div></div><div class="metric"><div class="metric-label">Kontak di database</div><div class="metric-value">${state.records.length}</div><div class="metric-trend">Tersimpan di workspace</div></div><div class="metric"><div class="metric-label">Siap di-follow-up</div><div class="metric-value">${ready}</div><div class="metric-trend">Berdasarkan readiness</div></div><div class="metric"><div class="metric-label">Review exceptions</div><div class="metric-value">${exceptions}</div><div class="metric-trend warning-text">Perlu perhatian PIC</div></div></section>
  <div class="grid-2"><section class="panel"><div class="panel-header"><div><h3>Aktivitas terbaru</h3><p>Proyek pencarian yang baru dikerjakan.</p></div><button class="text-button" data-go="projects">Lihat semua</button></div><div class="activity-list">${latest.map(p => `<div class="activity-item"><div class="avatar">${initials(p.name)}</div><div class="activity-copy"><strong>${esc(p.name)}</strong><span>${esc(p.focus)} · ${esc(p.region)} · ${esc(p.picName)}</span></div><span class="tag ${tagClass(p.status)}">${esc(p.status)}</span></div>`).join("")}</div></section><section class="panel"><div class="panel-header"><div><h3>Kualitas database</h3><p>Ringkasan kesiapan kontak.</p></div></div><div class="metric-value">${avg}%</div><p class="section-subtitle quality-subtitle">Rata-rata confidence</p><div class="progress-bar"><i style="width:${avg}%"></i></div><div class="mini-stat"><span>Kontak dengan email</span><strong>${state.records.filter(r => r.email && r.email !== "-").length}</strong></div><div class="mini-stat"><span>Sumber website resmi</span><strong>${state.records.filter(r => r.source === "Website resmi").length}</strong></div><div class="mini-stat"><span>Batas confidence</span><strong>${state.settings.minConfidence}%</strong></div></section></div>`;
}

function projectsView() {
  const rows = [...state.projects].sort((a,b) => new Date(b.createdAt) - new Date(a.createdAt)).map(p => `<tr><td><strong>${esc(p.name)}</strong><small>${esc(p.sources)} · mode ${esc(p.mode)} · PIC ${esc(p.picName)}</small></td><td>${esc(p.focus)}<small>Peran: ${esc(p.roleFocus || "Semua")}</small></td><td>${esc(p.region)}</td><td><strong>${p.resultIds.length}</strong><small>${esc(p.retrieval || "Belum ada ringkasan")}</small></td><td><span class="tag ${tagClass(p.status)}">${esc(p.status)}</span></td><td><div class="row-actions"><button class="table-action" data-open-project="${p.id}">Buka hasil</button>${p.backend ? `<button class="table-action" data-sync-project="${p.id}">Sinkronkan</button><button class="table-action muted-action" data-rerun="${p.id}">Cari ulang</button>` : `<button class="table-action muted-action" data-open-project="${p.id}">Lihat contoh</button>`}</div></td></tr>`).join("");
  return `<div class="section-heading"><div><div class="eyebrow">CONFIGURABLE SEARCH</div><h2 class="section-title">Semua Search Projects</h2><p class="section-subtitle">Proyek tersimpan bersama; setiap aktivitas membawa identitas PIC.</p></div><button class="primary-button" id="projectNewSearch">＋ New Search</button></div><div class="panel compact-panel"><div class="table-wrap"><table class="projects-table"><thead><tr><th>Project</th><th>Fokus</th><th>Wilayah</th><th>Hasil</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows || `<tr><td colspan="6"><div class="empty-state">Belum ada proyek pencarian.</div></td></tr>`}</tbody></table></div></div>`;
}
function projectOptions(includeAll = true) { return `${includeAll ? `<option value="all">Semua proyek</option>` : ""}${state.projects.map(p => `<option value="${p.id}" ${state.selectedProject === p.id ? "selected" : ""}>${esc(p.name)}</option>`).join("")}`; }
function resultRows(records) {
  if (!records.length) return `<tr><td colspan="7"><div class="empty-state"><div class="empty-icon">⌕</div>Tidak ada hasil yang cocok dengan filter.</div></td></tr>`;
  return records.map(r => `<tr><td><strong>${esc(r.institution)}</strong><small>${r.website ? `<a href="${esc(r.website)}" target="_blank" rel="noopener">Website resmi ↗</a>` : "Website belum tersedia"}</small></td><td>${esc(r.email || "-")}<small>${esc(r.phone || "-")}</small></td><td>${esc(r.address)}<small>${esc(r.region)}</small></td><td>${esc(r.category)}<small>${esc(r.role)}</small></td><td>${esc(r.evidence)}<small>${esc(r.source)}</small></td><td><strong>${r.confidence}%</strong><div class="confidence-bar"><i style="width:${r.confidence}%"></i></div></td><td><span class="tag ${tagClass(r.status)}">${esc(r.status)}</span><button class="table-action block-action" data-detail="${r.id}">Review</button></td></tr>`).join("");
}
function reviewView() {
  const selected = state.projects.find(p => p.id === state.selectedProject); const records = projectRecords(state.selectedProject); const avg = Math.round(records.reduce((s,r) => s + r.confidence, 0) / Math.max(records.length,1));
  return `<div class="eyebrow">EXCEPTION-BASED REVIEW</div><h2 class="section-title">Hasil Pencarian &amp; Review</h2><p class="section-subtitle">Gunakan filter untuk memprioritaskan hasil yang membutuhkan keputusan PIC.</p>
  <div class="panel filter-panel"><div class="filter-grid"><div class="form-field"><label>Search Project</label><select id="reviewProject">${projectOptions(true)}</select></div><div class="form-field"><label>Cari hasil</label><input id="reviewSearch" placeholder="Nama, email, kota..." /></div><div class="form-field"><label>Confidence minimum</label><input id="confidenceFilter" type="number" min="0" max="100" value="${state.settings.minConfidence}" /></div><div class="form-field"><label>Readiness</label><select id="readinessFilter"><option value="">Semua readiness</option><option>Siap Dihubungi</option><option>Belum Dihubungi</option><option>Follow-up</option><option>Perlu Verifikasi</option></select></div><div class="form-field"><label>Status review</label><select id="reviewStatus"><option value="">Semua status</option><option>Auto-stored</option><option>Disetujui</option><option>Perlu Review</option><option>Ditolak</option></select></div></div></div>
  ${selected ? `<div class="project-summary"><div><strong>${esc(selected.name)}</strong><span>${esc(selected.focus)} · ${esc(selected.region)} · mode ${esc(selected.mode)}</span></div><div><small>Creator PIC</small><strong>${esc(selected.picName)}</strong></div><div><small>Hasil</small><strong>${records.length} kontak</strong></div><div><small>Rata-rata confidence</small><strong>${avg}%</strong></div><button class="outline-button" data-rerun="${selected.id}">Lanjutkan Search</button></div>` : ""}
  <div class="filter-summary" id="reviewSummary">Menampilkan ${records.length} hasil · quality gate ${state.settings.minConfidence}%</div><div class="panel compact-panel"><div class="table-wrap"><table class="results-table"><thead><tr><th>Nama / Organisasi</th><th>Email / Telepon</th><th>Alamat / Wilayah</th><th>Kategori / Peran</th><th>Evidence</th><th>Confidence</th><th>Status</th></tr></thead><tbody id="reviewRows">${resultRows(records)}</tbody></table></div></div>`;
}

function databaseRows(records) {
  if (!records.length) return `<tr><td colspan="8"><div class="empty-state">Tidak ada data yang cocok.</div></td></tr>`;
  return records.map(r => `<tr><td><strong>${esc(r.institution)}</strong><small>${esc(r.category)}</small></td><td>${esc(r.role)}</td><td>${esc(r.email)}<small>${esc(r.phone)}</small></td><td>${esc(r.region)}</td><td>${r.confidence}%</td><td><span class="tag ${tagClass(r.readiness)}">${esc(r.readiness)}</span></td><td><span class="tag ${tagClass(r.status)}">${esc(r.status)}</span></td><td><button class="table-action" data-detail="${r.id}">Detail</button></td></tr>`).join("");
}
function databaseView() {
  const regions = [...new Set(state.records.map(r => r.region))].sort(); const categories = [...new Set(state.records.map(r => r.category))].sort();
  return `<div class="section-heading"><div><div class="eyebrow">MASTER RECORDS</div><h2 class="section-title">Master Database</h2><p class="section-subtitle">Gabungan semua kontak hasil pencarian dan data impor.</p></div><div class="button-row"><button class="outline-button" id="importButton">⇧ Import CSV/TSV</button><button class="primary-button" id="databaseExport">⇩ Export CSV</button></div></div><div class="panel filter-panel"><div class="filter-grid database-filters"><div class="form-field wide"><label>Cari database</label><input id="dbSearch" placeholder="Kampus, email, peran, alamat..." /></div><div class="form-field"><label>Wilayah</label><select id="dbRegion"><option value="">Semua wilayah</option>${regions.map(v => `<option>${esc(v)}</option>`).join("")}</select></div><div class="form-field"><label>Kategori</label><select id="dbCategory"><option value="">Semua kategori</option>${categories.map(v => `<option>${esc(v)}</option>`).join("")}</select></div><div class="form-field"><label>Status</label><select id="dbStatus"><option value="">Semua status</option><option>Auto-stored</option><option>Disetujui</option><option>Perlu Review</option><option>Ditolak</option></select></div></div></div><div class="filter-summary" id="dbSummary">${state.records.length} kontak tersimpan</div><div class="panel compact-panel"><div class="table-wrap"><table><thead><tr><th>Institusi</th><th>Kontak tujuan</th><th>Email / Telepon</th><th>Wilayah</th><th>Confidence</th><th>Readiness</th><th>Status</th><th></th></tr></thead><tbody id="dbRows">${databaseRows(state.records)}</tbody></table></div></div>`;
}

function downloadView() {
  return `<div class="eyebrow">EXPORT WORKSPACE</div><h2 class="section-title">Download Center</h2><p class="section-subtitle">Unduh data sesuai proyek, kebutuhan review, atau seluruh master database.</p><div class="download-grid"><article class="panel export-card"><div class="export-icon">CSV</div><h3>Hasil per proyek</h3><p>Pilih proyek lalu unduh hasil lengkap beserta confidence, evidence, dan status review.</p><div class="form-field"><label>Search Project</label><select id="downloadProject">${projectOptions(true)}</select></div><button class="primary-button full-button" id="downloadProjectCsv">Download CSV</button></article><article class="panel export-card"><div class="export-icon">!</div><h3>Review exceptions</h3><p>Unduh hanya data ber-confidence rendah atau berstatus Perlu Review.</p><div class="export-count">${state.records.filter(r => r.status === "Perlu Review" || r.confidence < state.settings.minConfidence).length} kontak</div><button class="outline-button full-button" id="downloadExceptions">Download exceptions</button></article><article class="panel export-card"><div class="export-icon">{ }</div><h3>Backup workspace</h3><p>Simpan seluruh proyek, kontak, dan pengaturan sebagai berkas JSON.</p><div class="export-count">${state.projects.length} proyek · ${state.records.length} kontak</div><button class="outline-button full-button" id="downloadJson">Download JSON</button></article></div>${state.downloadLog.length ? `<section class="panel download-history"><div class="panel-header"><div><h3>Riwayat unduhan</h3><p>Tersimpan di browser ini.</p></div></div>${state.downloadLog.map(log => `<div class="mini-stat"><span>${esc(log.name)}</span><strong>${fmtDate(log.at)}</strong></div>`).join("")}</section>` : ""}`;
}
function settingsView() {
  return `<div class="eyebrow">CONNECTION &amp; QUALITY</div><h2 class="section-title">Settings &amp; Safety</h2><p class="section-subtitle">Atur Google Sheets sebagai backend crawler dan quality gate workspace.</p><div class="settings-grid"><section class="panel"><div class="panel-header"><div><h3>Backend Google Sheets</h3><p>Apps Script menerima proyek, memproses antrean URL, dan mengembalikan hasil crawl.</p></div><span class="tag ${state.settings.sheetEndpoint ? "green" : "red"}">${state.settings.sheetEndpoint ? "Backend aktif" : "Belum tersambung"}</span></div><form id="settingsForm" class="form-grid"><div class="form-field full"><label>Google Apps Script Web App URL</label><input name="sheetEndpoint" value="${esc(state.settings.sheetEndpoint)}" placeholder="https://script.google.com/macros/s/.../exec" /></div><div class="form-field"><label>Minimum confidence (%)</label><input name="minConfidence" type="number" min="0" max="100" value="${state.settings.minConfidence}" /></div><div class="form-field"><label>Public Web Safe Mode</label><select name="safeMode"><option value="true" ${state.settings.safeMode ? "selected" : ""}>Aktif</option><option value="false" ${!state.settings.safeMode ? "selected" : ""}>Nonaktif</option></select></div><div class="form-actions full"><button type="button" class="outline-button" id="validateEndpoint">Tes backend</button><button class="primary-button">Simpan pengaturan</button></div></form></section><section class="panel"><div class="panel-header"><div><h3>Tab backend</h3><p>Dibuat otomatis oleh fungsi setupCrawler().</p></div></div><ul class="clean-list"><li><strong>Search_Projects</strong> — konfigurasi dan status</li><li><strong>Crawl_Queue</strong> — antrean URL dan error</li><li><strong>Crawl_Results</strong> — kontak hasil ekstraksi</li><li><strong>Sheet1</strong> — log pencarian ringkas</li></ul><div class="notice small-notice"><div><div class="notice-title">Crawler sumber publik</div><p>Hanya URL HTTP/HTTPS publik; robots.txt dan pembatasan halaman diterapkan.</p></div></div></section></div>`;
}
function helpView() {
  return `<div class="eyebrow">QUICK GUIDE</div><h2 class="section-title">Bantuan</h2><p class="section-subtitle">Alur kerja crawling dari URL publik hingga follow-up.</p><div class="help-grid"><article class="panel help-card"><span>1</span><h3>Isi identitas PIC</h3><p>Masukkan nama dan email/ID. Identitas ini melekat pada proyek dan keputusan review.</p></article><article class="panel help-card"><span>2</span><h3>Tambahkan URL sumber</h3><p>Masukkan satu atau beberapa website resmi kampus. Apps Script memasukkannya ke Crawl_Queue.</p></article><article class="panel help-card"><span>3</span><h3>Sinkronkan hasil</h3><p>Crawler membaca halaman publik dan kontak, lalu menyimpannya di Crawl_Results.</p></article><article class="panel help-card"><span>4</span><h3>Review dan unduh</h3><p>Periksa confidence/evidence, tandai status, dan ekspor hasil untuk follow-up.</p></article></div><section class="panel faq"><h3>Batasan aman</h3><p>Crawler berjalan di Google Apps Script dan Google Sheets. Hanya URL publik yang dimasukkan pengguna, maksimal delapan halaman relevan per sumber. Situs yang memerlukan login, CAPTCHA, LinkedIn, jaringan lokal, dan halaman yang dilarang robots.txt tidak diproses.</p><button class="primary-button" data-go="projects">Buka Search Projects</button></section>`;
}

function openModal(type, data = {}) {
  if (type === "search" && !state.pic.name) { state.pendingSearch = true; return openModal("pic"); }
  if (type === "pic") modalBody.innerHTML = `<h2>Identitas PIC</h2><p>Tidak perlu login atau password. Identitas ini dipakai untuk jejak aktivitas bersama.</p><form id="picForm" class="form-grid"><div class="form-field full"><label>Nama lengkap *</label><input name="name" required value="${esc(state.pic.name)}" /></div><div class="form-field full"><label>Email atau ID internal *</label><input name="contact" required value="${esc(state.pic.contact)}" /></div><div class="form-field full"><label>Unit / tim (opsional)</label><input name="unit" value="${esc(state.pic.unit)}" /></div><div class="form-actions full"><button type="button" class="secondary-button" data-close>Batal</button><button class="primary-button">Simpan identitas</button></div></form>`;
  if (type === "search") modalBody.innerHTML = `<h2>New Search Project</h2><p>Google Apps Script akan mengunjungi URL publik, menyimpan antrean dan hasilnya langsung di Google Sheets.</p><form id="searchForm" class="form-grid"><div class="form-field full"><label>Nama project *</label><input name="project" required placeholder="Contoh: Kontak kampus vokasi Jawa Barat" /></div><div class="form-field full"><label>URL website sumber *</label><textarea name="sourceUrls" required placeholder="https://kampus.ac.id\nhttps://kampus-lain.ac.id"></textarea><small>Satu URL per baris, maksimal 20. Gunakan situs resmi/publik.</small></div><div class="form-field full"><label>Fokus pencarian *</label><textarea name="focus" required placeholder="Kontak humas dan kerja sama untuk program sertifikasi"></textarea></div><div class="form-field"><label>Wilayah</label><input name="region" value="Indonesia" /></div><div class="form-field"><label>Kategori</label><select name="category"><option>Semua</option><option>Universitas</option><option>Institut</option><option>Politeknik</option><option>Sekolah Tinggi</option></select></div><div class="form-field full"><label>Fokus peran</label><input name="roleFocus" placeholder="Humas, Kerja Sama, Akademik" /></div><div class="form-field"><label>Mode crawl</label><select name="mode"><option>Deep</option><option>Strict</option><option>Quick</option></select></div><div class="form-field"><label>Kata kunci tambahan</label><input name="keywords" placeholder="sertifikasi, pelatihan" /></div><div class="form-actions full"><button type="button" class="secondary-button" data-close>Batal</button><button class="primary-button">Kirim ke crawler</button></div></form>`;
  if (type === "detail") { const r = data; modalBody.innerHTML = `<div class="detail-title"><div class="avatar large-avatar">${initials(r.institution)}</div><div><h2>${esc(r.institution)}</h2><p>${esc(r.category)} · ${esc(r.region)}</p></div></div><div class="detail-grid"><div><small>Kontak tujuan</small><strong>${esc(r.role)}</strong></div><div><small>Confidence</small><strong>${r.confidence}%</strong></div><div><small>Email</small><strong>${esc(r.email)}</strong></div><div><small>Telepon</small><strong>${esc(r.phone)}</strong></div><div class="full"><small>Evidence</small><strong>${esc(r.evidence)}</strong></div><div class="full"><small>Alamat</small><strong>${esc(r.address)}</strong></div></div><div class="form-field status-editor"><label>Keputusan PIC</label><select id="detailStatus"><option ${r.status === "Auto-stored" ? "selected" : ""}>Auto-stored</option><option ${r.status === "Disetujui" ? "selected" : ""}>Disetujui</option><option ${r.status === "Perlu Review" ? "selected" : ""}>Perlu Review</option><option ${r.status === "Ditolak" ? "selected" : ""}>Ditolak</option></select></div><div class="form-actions"><button class="secondary-button" id="markFollowup">Tandai follow-up</button><button class="primary-button" id="saveReview">Simpan review</button></div>`; }
  modalBackdrop.hidden = false;
  modalBody.querySelectorAll("[data-close]").forEach(b => b.addEventListener("click", closeModal));
  document.getElementById("picForm")?.addEventListener("submit", (e) => { e.preventDefault(); state.pic = Object.fromEntries(new FormData(e.target)); persist(); closeModal(); render(); showToast("Identitas PIC berhasil disimpan"); if (state.pendingSearch) { state.pendingSearch = false; setTimeout(() => openModal("search"), 120); } });
  document.getElementById("searchForm")?.addEventListener("submit", createSearch);
  document.getElementById("saveReview")?.addEventListener("click", () => { data.status = document.getElementById("detailStatus").value; persist(); closeModal(); render(); showToast(`Review disimpan atas nama ${state.pic.name || "PIC"}`); });
  document.getElementById("markFollowup")?.addEventListener("click", () => { data.readiness = "Follow-up"; persist(); closeModal(); render(); showToast("Kontak ditandai untuk follow-up"); });
}
function closeModal() { modalBackdrop.hidden = true; modalBody.innerHTML = ""; }
async function createSearch(event) {
  event.preventDefault(); const form = Object.fromEntries(new FormData(event.target));
  const project = { id: `prj-${Date.now()}`, name: form.project, focus: form.focus, roleFocus: form.roleFocus || "Semua peran", region: form.region || "Indonesia", category: form.category, mode: form.mode, sources: "Google Sheets crawler", sourceUrls: form.sourceUrls, keywords: form.keywords || "", backend: true, status: "Sedang mencari", resultIds: [], createdAt: new Date().toISOString(), picName: state.pic.name, retrieval: "Dikirim ke Crawl_Queue..." };
  state.projects.unshift(project); state.selectedProject = project.id; persist(); closeModal(); state.view = "projects"; render();
  const payload = { action: "create_search", type: "search", projectId: project.id, createdAt: project.createdAt, project: project.name, sourceUrls: project.sourceUrls, region: project.region, category: project.category, focus: project.focus, keywords: project.keywords, roleFocus: project.roleFocus, picName: state.pic.name, picContact: state.pic.contact, picRole: state.pic.unit, status: "Sedang mencari", mode: project.mode };
  const synced = await submitCrawlerJob(payload);
  project.retrieval = synced ? "Crawler sedang memproses URL publik..." : "Gagal menghubungi backend; periksa Settings & Safety";
  if (!synced) project.status = "Error";
  persist(); render();
  showToast(synced ? "Project masuk ke Google Sheets crawler" : "Backend Google Sheets tidak dapat dihubungi");
  if (synced) setTimeout(() => refreshProjectFromSheet(project.id, true), 1600);
}
async function submitCrawlerJob(payload) { if (!state.settings.sheetEndpoint) return false; try { await fetch(state.settings.sheetEndpoint, { method: "POST", mode: "no-cors", headers: { "Content-Type": "text/plain;charset=utf-8" }, body: JSON.stringify(payload) }); return true; } catch (error) { console.warn("Google Sheets crawler submit failed", error); return false; } }
function jsonpRequest(params, timeoutMs = 20000, endpoint = state.settings.sheetEndpoint) {
  return new Promise((resolve, reject) => {
    if (!endpoint) return reject(new Error("Endpoint belum diatur"));
    const callback = `__kampusReach_${Date.now()}_${Math.random().toString(36).slice(2)}`;
    const script = document.createElement("script");
    const cleanup = () => { delete window[callback]; script.remove(); clearTimeout(timer); };
    window[callback] = data => { cleanup(); resolve(data); };
    const timer = setTimeout(() => { cleanup(); reject(new Error("Backend timeout")); }, timeoutMs);
    script.onerror = () => { cleanup(); reject(new Error("Backend tidak dapat dibaca")); };
    const query = new URLSearchParams({ ...params, callback, _: String(Date.now()) });
    script.src = `${endpoint}?${query}`;
    document.head.appendChild(script);
  });
}
async function refreshProjectFromSheet(id, announce = false) {
  const project = state.projects.find(p => p.id === id); if (!project || !project.backend) return false;
  try {
    const bundle = await jsonpRequest({ action: "status", projectId: id });
    if (!bundle?.ok) throw new Error(bundle?.error || "Respons backend tidak valid");
    const remote = (bundle.results || []).map(record => ({ ...record, id: String(record.id), crawlProjectId: id }));
    state.records = state.records.filter(record => record.crawlProjectId !== id).concat(remote);
    project.resultIds = remote.map(record => record.id);
    project.status = bundle.project.status;
    project.retrieval = `${bundle.project.processedUrls}/${bundle.project.totalUrls} URL diproses · ${remote.length} kontak`;
    project.backendError = bundle.project.error || "";
    persist(); if (state.view === "projects" || state.view === "review" || state.view === "dashboard") render();
    if (announce) showToast(project.status === "Sedang mencari" ? "Crawler masih bekerja; sinkronkan kembali sebentar lagi" : `${remote.length} hasil disinkronkan dari Google Sheets`);
    return true;
  } catch (error) {
    project.retrieval = `Sinkronisasi gagal: ${error.message}`; persist(); if (state.view === "projects") render(); if (announce) showToast(project.retrieval); return false;
  }
}
async function rerunProject(id) {
  const project = state.projects.find(p => p.id === id); if (!project || !project.backend || !project.sourceUrls) return showToast("Proyek contoh tidak memiliki antrean crawler");
  project.status = "Sedang mencari"; project.retrieval = "Mengantrekan ulang URL..."; project.createdAt = new Date().toISOString(); project.picName = state.pic.name || project.picName; persist(); render();
  const ok = await submitCrawlerJob({ action: "rerun_search", projectId: project.id, sourceUrls: project.sourceUrls });
  showToast(ok ? "URL dimasukkan kembali ke Crawl_Queue" : "Gagal menghubungi backend crawler");
  if (ok) setTimeout(() => refreshProjectFromSheet(project.id, true), 1600);
}

function bindViewEvents() {
  document.querySelectorAll("[data-go]").forEach(b => b.addEventListener("click", () => { state.view = b.dataset.go; render(); }));
  document.getElementById("noticePicButton")?.addEventListener("click", () => openModal("pic")); document.getElementById("heroSearch")?.addEventListener("click", () => openModal("search")); document.getElementById("projectNewSearch")?.addEventListener("click", () => openModal("search"));
  document.querySelectorAll("[data-detail]").forEach(b => b.addEventListener("click", () => openModal("detail", state.records.find(r => String(r.id) === String(b.dataset.detail)))));
  document.querySelectorAll("[data-open-project]").forEach(b => b.addEventListener("click", async () => { const id = b.dataset.openProject; const project = state.projects.find(item => item.id === id); if (project?.backend) await refreshProjectFromSheet(id, false); state.selectedProject = id; state.view = "review"; persist(); render(); }));
  document.querySelectorAll("[data-rerun]").forEach(b => b.addEventListener("click", () => rerunProject(b.dataset.rerun)));
  document.querySelectorAll("[data-sync-project]").forEach(b => b.addEventListener("click", () => refreshProjectFromSheet(b.dataset.syncProject, true)));
  bindReviewFilters(); bindDatabaseFilters(); bindDownloads(); bindSettings();
  document.getElementById("importButton")?.addEventListener("click", () => document.getElementById("importInput").click()); document.getElementById("databaseExport")?.addEventListener("click", () => downloadCsv(state.records, "kampusreach-master-database.csv"));
}
function bindReviewFilters() {
  const project = document.getElementById("reviewProject"); const search = document.getElementById("reviewSearch"); const confidence = document.getElementById("confidenceFilter"); const readiness = document.getElementById("readinessFilter"); const status = document.getElementById("reviewStatus"); if (!project) return;
  project.addEventListener("change", () => { state.selectedProject = project.value; persist(); render(); });
  const apply = () => { const q = search.value.toLowerCase(); const min = Number(confidence.value || 0); const rows = projectRecords(state.selectedProject).filter(r => r.confidence >= min && (!readiness.value || r.readiness === readiness.value) && (!status.value || r.status === status.value) && Object.values(r).join(" ").toLowerCase().includes(q)); document.getElementById("reviewRows").innerHTML = resultRows(rows); document.getElementById("reviewSummary").textContent = `Menampilkan ${rows.length} hasil · confidence minimum ${min}%`; document.querySelectorAll("[data-detail]").forEach(b => b.addEventListener("click", () => openModal("detail", state.records.find(r => String(r.id) === String(b.dataset.detail))))); };
  [search, confidence, readiness, status].forEach(el => el.addEventListener(el.tagName === "INPUT" ? "input" : "change", apply));
}
function bindDatabaseFilters() {
  const search = document.getElementById("dbSearch"); if (!search) return; const region = document.getElementById("dbRegion"); const category = document.getElementById("dbCategory"); const status = document.getElementById("dbStatus");
  const apply = () => { const q = search.value.toLowerCase(); const rows = state.records.filter(r => (!region.value || r.region === region.value) && (!category.value || r.category === category.value) && (!status.value || r.status === status.value) && Object.values(r).join(" ").toLowerCase().includes(q)); document.getElementById("dbRows").innerHTML = databaseRows(rows); document.getElementById("dbSummary").textContent = `${rows.length} dari ${state.records.length} kontak`; document.querySelectorAll("[data-detail]").forEach(b => b.addEventListener("click", () => openModal("detail", state.records.find(r => String(r.id) === String(b.dataset.detail))))); };
  search.addEventListener("input", apply); [region,category,status].forEach(el => el.addEventListener("change", apply));
}
function bindDownloads() {
  document.getElementById("downloadProject")?.addEventListener("change", e => { state.selectedProject = e.target.value; persist(); });
  document.getElementById("downloadProjectCsv")?.addEventListener("click", () => downloadCsv(projectRecords(document.getElementById("downloadProject").value), "kampusreach-hasil-project.csv"));
  document.getElementById("downloadExceptions")?.addEventListener("click", () => downloadCsv(state.records.filter(r => r.status === "Perlu Review" || r.confidence < state.settings.minConfidence), "kampusreach-review-exceptions.csv"));
  document.getElementById("downloadJson")?.addEventListener("click", () => downloadFile(JSON.stringify({ exportedAt: new Date().toISOString(), projects: state.projects, records: state.records, settings: { minConfidence: state.settings.minConfidence, safeMode: state.settings.safeMode } }, null, 2), "kampusreach-workspace-backup.json", "application/json"));
}
function bindSettings() {
  document.getElementById("validateEndpoint")?.addEventListener("click", async () => { const value = document.querySelector('[name="sheetEndpoint"]').value.trim(); if (!/^https:\/\/script\.google\.com\/macros\/s\/.+\/exec$/.test(value)) return showToast("Alamat harus berupa URL Web App Google Apps Script"); try { const ping = await jsonpRequest({ action: "ping" }, 15000, value); showToast(ping?.ok ? `Backend terhubung · ${ping.service}` : "Backend merespons tetapi belum siap"); } catch (error) { showToast(`Tes backend gagal: ${error.message}`); } });
  document.getElementById("settingsForm")?.addEventListener("submit", e => { e.preventDefault(); const values = Object.fromEntries(new FormData(e.target)); state.settings.sheetEndpoint = values.sheetEndpoint.trim(); state.settings.minConfidence = Math.max(0, Math.min(100, Number(values.minConfidence || 0))); state.settings.safeMode = values.safeMode === "true"; persist(); render(); showToast("Pengaturan berhasil disimpan"); });
}
function downloadCsv(records, filename) { const headers = ["Institusi","Kategori","Peran","Email","Telepon","Alamat","Wilayah","Website","Confidence","Readiness","Status","Evidence","Sumber"]; const rows = records.map(r => [r.institution,r.category,r.role,r.email,r.phone,r.address,r.region,r.website,r.confidence,r.readiness,r.status,r.evidence,r.source]); const csv = [headers,...rows].map(row => row.map(value => `"${String(value ?? "").replaceAll('"','""')}"`).join(",")).join("\r\n"); downloadFile(`\uFEFF${csv}`, filename, "text/csv;charset=utf-8"); }
function downloadFile(data, filename, type) { const blob = new Blob([data], { type }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url); state.downloadLog.unshift({ name: filename, at: new Date().toISOString() }); state.downloadLog = state.downloadLog.slice(0,12); persist(); showToast(`${filename} berhasil dibuat`); }

document.querySelectorAll(".nav-item").forEach(item => item.addEventListener("click", () => { state.view = item.dataset.view; render(); }));
document.getElementById("picButton").addEventListener("click", () => openModal("pic")); document.getElementById("newSearchButton").addEventListener("click", () => openModal("search"));
document.getElementById("themeButton").addEventListener("click", () => { state.theme = state.theme === "dark" ? "light" : "dark"; document.body.classList.toggle("dark", state.theme === "dark"); localStorage.setItem("kampus-theme", state.theme); });
document.getElementById("menuButton").addEventListener("click", () => document.getElementById("sidebar").classList.toggle("open")); document.getElementById("modalClose").addEventListener("click", closeModal); modalBackdrop.addEventListener("click", event => { if (event.target === modalBackdrop) closeModal(); }); document.getElementById("importInput").addEventListener("change", importFile);
function importFile(event) {
  const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const lines = String(reader.result).split(/\r?\n/).filter(Boolean); const delimiter = file.name.toLowerCase().endsWith(".tsv") ? "\t" : ","; const start = /institusi|institution|nama/i.test(lines[0]) ? 1 : 0; const imported = lines.slice(start).map((line,index) => { const c = line.split(delimiter).map(v => v.trim().replace(/^"|"$/g,"")); return { id: Date.now()+index, institution: c[0] || "Institusi tanpa nama", category: c[1] || "Perguruan Tinggi", role: c[2] || "Kontak umum", email: c[3] || "-", phone: c[4] || "-", address: c[5] || "-", region: c[6] || "Indonesia", website: c[7] || "", confidence: Number(c[8]) || 60, readiness: c[9] || "Belum Dihubungi", status: c[10] || "Perlu Review", evidence: c[11] || "Data impor", source: "Data impor" }; }).filter(r => r.institution !== "Institusi tanpa nama"); state.records = [...state.records,...imported]; persist(); render(); showToast(`${imported.length} baris berhasil diimpor`); }; reader.readAsText(file); event.target.value = "";
}
render();
